apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-dev-app
  namespace: sandbox-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-dev-app
  template:
    metadata:
      labels:
        app: node-dev-app
    spec:
      containers:
      - name: node-dev-app
        image: mukeshdani/node-dev-app:v1.0
        ports:
        - containerPort: 3000
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1000  
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
      - name: regcred
