apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-sandbox
  namespace: sandbox-app
subjects:
- kind: User
  name: 30116358@adani.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
