apiVersion: v1
kind: Service
metadata:
  name: node-dev-app
  namespace: sandbox-app
spec:
  type: LoadBalancer
  selector:
    app: node-dev-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
