apiVersion: v1
kind: Service
metadata:
  name: node-dev-app
  namespace: sandbox-app
spec:
  selector:
    app: node-dev-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
